### ISSUE TITLE
Separate LED from MQTT

### ISSUE THREAD

**Issue by Vendo232** [jamesbattersby/esp8266-landing-lights#3]
Hi

would it be possible to separate LED (250ms ) from MQTT publishing? Sending every 250ms a MQTT is not neccessary, instead publishing MQTT distance every ~15min ( adjustable ) could provide information if CAR is or not in the garage.

**Comment by jamesbattersby** [comment]
As the distance is measured every 250ms, the simplest way would be to have the notify function send a message every 60th call, this would get your ~15 min notifications.
